### ISSUE TITLE
Feature request: Android support

### ISSUE THREAD

**Issue by videgro** [viraptor/kalibrate-rtl#14]
It would be great when Android is supported by kalibrate-rtl too.

In that case I can integrate it in my Ships application. This is an Android application which receives ship data (AIS) using a SDR-RTL device.
More info: https://github.com/videgro/Ships

**Comment by viraptor** [comment]
Sorry, this is completely out of scope. If anyone wants to implement/test it, I'm happy to merge it, but I have no skills in Android native dev.
