### ISSUE TITLE
Irregular output

### ISSUE THREAD

**Issue by RomanHargrave** [viraptor/kalibrate-rtl#3]
As stated, output varies too much channels and modes, for instance, when calibrated against \#998 (E-GSM-900), the determined clock error is 11.787 PPM, but when calibrated against \#29 (GSM-900) the determined clock error is 29.680, and \#85 yields -0.126 PPM. 

Multiple calibrations against the same channel yield consistent results, so why don't multiple calibrations against different channels?

I noticed that someone also mentioned this problem on the kalibrate-hackrf tracker, so while radio implementation is _technically_ possible, software issues seem more likely.

**Comment by viraptor** [comment]
You're using the -rtl version, which are usually cheap / inaccurate devices. You need to do a general tuning to something like a local FM station, before using kalibrate with the `-e` parameter to set the initial error you find.
Then you should start getting consistent results between channels with the right PPM.

Original kalibrate worked well for things like USRP1, which was documented as:

> The USRP1, similar to a number of devices, has a built-in oscillator which is only guaranteed accurate to within 20 parts per million (ppm)

The rtl version is off by a lot more. My rtl dongle is PPM of -743 for example. Without the initial correction (of -730), it picked up wrong GSM channels which resulted in suggested PPM of either 39 or -20. With the correction, it gets within 0.5 PPM between those channels.

**Comment by viraptor** [comment]
I started a different project for large offsets. If you want to get an initial estimate that works up to ~1000PPM, you can check out https://github.com/viraptor/fm_tune
