### ISSUE TITLE
Error when compiling: README not found

### ISSUE THREAD

**Issue by pachulo** [viraptor/kalibrate-rtl#7]
When I try to compile the software:

`./bootstrap && CXXFLAGS='-W -Wall -O3' && ./configure && make && make install`

I now get this error:

```
configure.ac:9: installing './compile'
configure.ac:37: installing './config.guess'
configure.ac:37: installing './config.sub'
configure.ac:4: installing './install-sh'
configure.ac:4: installing './missing'

Makefile.am: installing './INSTALL'
Makefile.am: error: required file './README' not found
```

Could it be because of this? https://github.com/viraptor/kalibrate-rtl/commit/308e4e16e4e62b2032bb2613695ca9843aa2be4a

**Comment by viraptor** [comment]
Thanks, I'll have a look at this.
